version: '3.9'
services:
  db:
    image: postgres:15.1
    container_name: db
    ports:
      - 3002:5432
    platform: linux/x86_64
    environment:
      - POSTGRES_USER=ngcash
      - POSTGRES_DB=ngcash
      - POSTGRES_PASSWORD=123456
    restart: 'always'
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      - db
    environment:
      - PORT=3001
      - JWT_SECRET=secret
      - DB_USER=ngcash
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=5432
  frontend:
    container_name: app_frontent
    build: ./frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      - backend
