version: '3.9'
services:
  db:
    image: postgres:15.1
    container_name: db
    ports:
      - 3002:5432
    environment:
      - POSTGRES_USER=ngcash
      - POSTGRES_DB=ngcash
      - POSTGRES_PASSWORD=123456
    restart: 'always'

